2021-09-16 11:54:28,835 [INFO] root consoleworker.py:434	Log file created
2021-09-16 11:54:28,835 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f9ef9ae3c10> added
2021-09-16 11:54:28,836 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f9ef9b2b850> added
2021-09-16 11:54:28,836 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f9ef9acfa50> added
2021-09-16 11:54:28,837 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-09-16_11-54-28.796447
2021-09-16 11:54:28,838 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-09-16 11:54:28,840 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-09-16 11:54:28,842 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-09-16 11:54:28,843 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin telegraf from yandextank.plugins.Telegraf
2021-09-16 11:54:28,844 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-09-16 11:54:28,845 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-09-16 11:54:28,850 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-09-16 11:54:28,851 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-09-16 11:54:28,851 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-09-16 11:54:28,852 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-09-16 11:54:28,853 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f9ef979a610>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f9ef979af50>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f9ef979ad90>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f9ef979acd0>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f9ef979ab10>, 'plugin_telegraf': <yandextank.plugins.Telegraf.plugin.Plugin object at 0x7f9ef979a590>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f9ef979a190>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f9ef979a310>}
2021-09-16 11:54:28,853 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f9ef979a610>
2021-09-16 11:54:28,854 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-09-16 11:54:28,863 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_11-54-28.796447/answ_OQeurb.log
2021-09-16 11:54:28,866 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_11-54-28.796447/phout_TFyH5R.log
2021-09-16 11:54:28,867 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_stat_OJbzs_.log
2021-09-16 11:54:28,871 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_PoF3ZO.log
2021-09-16 11:54:28,871 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 192.168.1.74:9999
2021-09-16 11:54:28,872 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-09-16 11:54:28,873 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.1.74', 9999)), (2, 2, 17, '', ('192.168.1.74', 9999)), (2, 3, 0, '', ('192.168.1.74', 9999))]
2021-09-16 11:54:28,873 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.74 and port 9999
2021-09-16 11:54:29,958 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.74]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 11:54:29,959 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.74]:9999
2021-09-16 11:54:29,960 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.74]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.74]:9999, use phantom.connection_test=0 to disable it
2021-09-16 11:54:29,965 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.74 and port 9999
2021-09-16 11:54:31,083 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.74]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 11:54:31,087 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.74]:9999
2021-09-16 11:54:31,089 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.74]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.74]:9999, use phantom.connection_test=0 to disable it
2021-09-16 11:54:31,091 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.74 and port 9999
2021-09-16 11:54:32,209 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.74]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 11:54:32,212 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.74]:9999
2021-09-16 11:54:32,214 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.74]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.74]:9999, use phantom.connection_test=0 to disable it
2021-09-16 11:54:32,220 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 192.168.1.74, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-09-16 11:54:32,225 [INFO] root consoleworker.py:269	Trying to clean up
2021-09-16 11:54:32,227 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark___DtRG.lock
2021-09-16 11:54:32,234 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-09-16 11:54:32,236 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-09-16 11:54:32,243 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-09-16 11:54:32,244 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-09-16_11-54-28.796447
2021-09-16 11:54:32,245 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_11-54-28.796447/phout_TFyH5R.log to /var/loadtest/logs/2021-09-16_11-54-28.796447/phout_TFyH5R.log
2021-09-16 11:54:32,246 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_11-54-28.796447/phout_TFyH5R.log
2021-09-16 11:54:32,249 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_stat_OJbzs_.log to /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_stat_OJbzs_.log
2021-09-16 11:54:32,250 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_stat_OJbzs_.log
2021-09-16 11:54:32,252 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_PoF3ZO.log to /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_PoF3ZO.log
2021-09-16 11:54:32,253 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_11-54-28.796447/phantom_PoF3ZO.log
2021-09-16 11:54:32,255 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-09-16_11-54-28.796447/validation_error.yaml
2021-09-16 11:54:32,257 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-09-16 11:54:32,258 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_11-54-28.796447/answ_OQeurb.log to /var/loadtest/logs/2021-09-16_11-54-28.796447/answ_OQeurb.log
2021-09-16 11:54:32,259 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_11-54-28.796447/answ_OQeurb.log
