2021-09-16 12:25:46,161 [INFO] root consoleworker.py:434	Log file created
2021-09-16 12:25:46,162 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7feaebc88c10> added
2021-09-16 12:25:46,163 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7feaebcd0850> added
2021-09-16 12:25:46,165 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7feaebc74a50> added
2021-09-16 12:25:46,166 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-09-16_12-25-46.111388
2021-09-16 12:25:46,168 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-09-16 12:25:46,171 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-09-16 12:25:46,172 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-09-16 12:25:46,173 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin telegraf from yandextank.plugins.Telegraf
2021-09-16 12:25:46,174 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-09-16 12:25:46,175 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-09-16 12:25:46,183 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-09-16 12:25:46,184 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-09-16 12:25:46,185 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-09-16 12:25:46,186 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-09-16 12:25:46,187 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7feaeb93f610>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7feaeb93ff50>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7feaeb93fd90>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7feaeb93fcd0>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7feaeb93fb10>, 'plugin_telegraf': <yandextank.plugins.Telegraf.plugin.Plugin object at 0x7feaeb93f590>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7feaeb93f190>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7feaeb93f310>}
2021-09-16 12:25:46,188 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7feaeb93f610>
2021-09-16 12:25:46,189 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-09-16 12:25:46,197 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-25-46.111388/answ_lamQBR.log
2021-09-16 12:25:46,201 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-25-46.111388/phout_UpBHCa.log
2021-09-16 12:25:46,201 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_stat_yi7pPb.log
2021-09-16 12:25:46,205 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_Hb3zSV.log
2021-09-16 12:25:46,206 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 192.168.1.73:9999
2021-09-16 12:25:46,207 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-09-16 12:25:46,207 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.1.73', 9999)), (2, 2, 17, '', ('192.168.1.73', 9999)), (2, 3, 0, '', ('192.168.1.73', 9999))]
2021-09-16 12:25:46,208 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 12:25:46,211 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 12:25:46,212 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 12:25:46,213 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 12:25:46,215 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 12:25:46,216 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 12:25:46,217 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 12:25:46,218 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 12:25:46,219 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 12:25:46,221 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 12:25:46,222 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 12:25:46,223 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 12:25:46,225 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 192.168.1.73, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-09-16 12:25:46,229 [INFO] root consoleworker.py:269	Trying to clean up
2021-09-16 12:25:46,230 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_W3yEm_.lock
2021-09-16 12:25:46,235 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-09-16 12:25:46,237 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-09-16 12:25:46,241 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-09-16 12:25:46,241 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-09-16_12-25-46.111388
2021-09-16 12:25:46,242 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_Hb3zSV.log to /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_Hb3zSV.log
2021-09-16 12:25:46,244 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_Hb3zSV.log
2021-09-16 12:25:46,246 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_stat_yi7pPb.log to /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_stat_yi7pPb.log
2021-09-16 12:25:46,247 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-25-46.111388/phantom_stat_yi7pPb.log
2021-09-16 12:25:46,250 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-25-46.111388/phout_UpBHCa.log to /var/loadtest/logs/2021-09-16_12-25-46.111388/phout_UpBHCa.log
2021-09-16 12:25:46,251 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-25-46.111388/phout_UpBHCa.log
2021-09-16 12:25:46,253 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-09-16_12-25-46.111388/validation_error.yaml
2021-09-16 12:25:46,256 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-09-16 12:25:46,258 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-25-46.111388/answ_lamQBR.log to /var/loadtest/logs/2021-09-16_12-25-46.111388/answ_lamQBR.log
2021-09-16 12:25:46,259 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-25-46.111388/answ_lamQBR.log
