2021-09-16 12:29:19,758 [INFO] root consoleworker.py:434	Log file created
2021-09-16 12:29:19,759 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f5e69417c10> added
2021-09-16 12:29:19,759 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f5e6945f850> added
2021-09-16 12:29:19,760 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f5e69403a50> added
2021-09-16 12:29:19,761 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-09-16_12-29-19.713135
2021-09-16 12:29:19,762 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-09-16 12:29:19,763 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-09-16 12:29:19,764 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-09-16 12:29:19,766 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin telegraf from yandextank.plugins.Telegraf
2021-09-16 12:29:19,767 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-09-16 12:29:19,769 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-09-16 12:29:19,775 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-09-16 12:29:19,775 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-09-16 12:29:19,776 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-09-16 12:29:19,777 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-09-16 12:29:19,777 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f5e690ce610>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f5e690cef50>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f5e690ced90>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f5e690cecd0>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f5e690ceb10>, 'plugin_telegraf': <yandextank.plugins.Telegraf.plugin.Plugin object at 0x7f5e690ce590>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f5e690ce190>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f5e690ce310>}
2021-09-16 12:29:19,778 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f5e690ce610>
2021-09-16 12:29:19,779 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-09-16 12:29:19,787 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-29-19.713135/answ_nsF84l.log
2021-09-16 12:29:19,791 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-29-19.713135/phout_ugLQB_.log
2021-09-16 12:29:19,792 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_stat__osGBt.log
2021-09-16 12:29:19,796 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_tWkhFF.log
2021-09-16 12:29:19,797 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 192.168.1.73:9999
2021-09-16 12:29:19,798 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-09-16 12:29:19,800 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.1.73', 9999)), (2, 2, 17, '', ('192.168.1.73', 9999)), (2, 3, 0, '', ('192.168.1.73', 9999))]
2021-09-16 12:29:19,801 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 12:29:19,803 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 12:29:19,804 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 12:29:19,805 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 12:29:19,806 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 12:29:24,787 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

2021-09-16 12:29:24,789 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 12:29:24,791 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 12:29:24,793 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 12:29:24,795 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 12:29:24,797 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 12:29:24,799 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 12:29:24,801 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 192.168.1.73, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-09-16 12:29:24,806 [INFO] root consoleworker.py:269	Trying to clean up
2021-09-16 12:29:24,807 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_sOsodY.lock
2021-09-16 12:29:24,811 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-09-16 12:29:24,813 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-09-16 12:29:24,818 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-09-16 12:29:24,819 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-09-16_12-29-19.713135
2021-09-16 12:29:24,820 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-29-19.713135/phout_ugLQB_.log to /var/loadtest/logs/2021-09-16_12-29-19.713135/phout_ugLQB_.log
2021-09-16 12:29:24,821 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-29-19.713135/phout_ugLQB_.log
2021-09-16 12:29:24,823 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_tWkhFF.log to /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_tWkhFF.log
2021-09-16 12:29:24,824 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_tWkhFF.log
2021-09-16 12:29:24,825 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_stat__osGBt.log to /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_stat__osGBt.log
2021-09-16 12:29:24,826 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-29-19.713135/phantom_stat__osGBt.log
2021-09-16 12:29:24,828 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-09-16_12-29-19.713135/validation_error.yaml
2021-09-16 12:29:24,829 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-09-16 12:29:24,831 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_12-29-19.713135/answ_nsF84l.log to /var/loadtest/logs/2021-09-16_12-29-19.713135/answ_nsF84l.log
2021-09-16 12:29:24,833 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_12-29-19.713135/answ_nsF84l.log
