2021-09-16 13:18:22,204 [INFO] root consoleworker.py:434	Log file created
2021-09-16 13:18:22,204 [INFO] root consoleworker.py:438	Logging handler <logging.FileHandler object at 0x7f76b299bc10> added
2021-09-16 13:18:22,205 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f76b29e3850> added
2021-09-16 13:18:22,206 [INFO] root consoleworker.py:438	Logging handler <logging.StreamHandler object at 0x7f76b2987a50> added
2021-09-16 13:18:22,207 [INFO] root consoleworker.py:373	Created a folder for the test. /var/loadtest/logs/2021-09-16_13-18-22.140184
2021-09-16 13:18:22,208 [INFO] yandextank.core.tankcore tankcore.py:237	Configuring plugins...
2021-09-16 13:18:22,209 [INFO] yandextank.core.tankcore tankcore.py:190	Loading plugins...
2021-09-16 13:18:22,209 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin phantom from yandextank.plugins.Phantom
2021-09-16 13:18:22,210 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin telegraf from yandextank.plugins.Telegraf
2021-09-16 13:18:22,211 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcheck from yandextank.plugins.ResourceCheck
2021-09-16 13:18:22,212 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin json_report from yandextank.plugins.JsonReport
2021-09-16 13:18:22,217 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin rcassert from yandextank.plugins.RCAssert
2021-09-16 13:18:22,218 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin console from yandextank.plugins.Console
2021-09-16 13:18:22,219 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin shellexec from yandextank.plugins.ShellExec
2021-09-16 13:18:22,220 [DEBUG] yandextank.core.tankcore tankcore.py:192	Loading plugin autostop from yandextank.plugins.Autostop
2021-09-16 13:18:22,221 [DEBUG] yandextank.core.tankcore tankcore.py:212	Plugin instances: {'plugin_phantom': <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f76b2652610>, 'plugin_autostop': <yandextank.plugins.Autostop.plugin.Plugin object at 0x7f76b2652f50>, 'plugin_shellexec': <yandextank.plugins.ShellExec.plugin.Plugin object at 0x7f76b2652d90>, 'plugin_console': <yandextank.plugins.Console.plugin.Plugin object at 0x7f76b2652cd0>, 'plugin_rcassert': <yandextank.plugins.RCAssert.plugin.Plugin object at 0x7f76b2652b10>, 'plugin_telegraf': <yandextank.plugins.Telegraf.plugin.Plugin object at 0x7f76b2652590>, 'plugin_rcheck': <yandextank.plugins.ResourceCheck.plugin.Plugin object at 0x7f76b2652190>, 'plugin_json_report': <yandextank.plugins.JsonReport.plugin.Plugin object at 0x7f76b2652310>}
2021-09-16 13:18:22,221 [DEBUG] yandextank.core.tankcore tankcore.py:244	Configuring <yandextank.plugins.Phantom.plugin.Plugin object at 0x7f76b2652610>
2021-09-16 13:18:22,223 [DEBUG] yandextank.core.tankcore tankcore.py:391	Searching for plugin: <class 'yandextank.plugins.Autostop.plugin.Plugin'>
2021-09-16 13:18:22,231 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-18-22.140184/answ_QWPvKk.log
2021-09-16 13:18:22,237 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-18-22.140184/phout__sJeLe.log
2021-09-16 13:18:22,238 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_stat_BOdlua.log
2021-09-16 13:18:22,243 [DEBUG] yandextank.core.tankcore tankcore.py:446	Adding artifact file to collect (keep=False): /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_H1szRI.log
2021-09-16 13:18:22,244 [DEBUG] yandextank.common.util util.py:479	Trying to resolve address string: 192.168.1.73:9999
2021-09-16 13:18:22,246 [DEBUG] yandextank.common.util util.py:516	Parsing port
2021-09-16 13:18:22,247 [DEBUG] yandextank.common.util util.py:527	Lookup result: [(2, 1, 6, '', ('192.168.1.73', 9999)), (2, 2, 17, '', ('192.168.1.73', 9999)), (2, 3, 0, '', ('192.168.1.73', 9999))]
2021-09-16 13:18:22,248 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 13:18:22,251 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 13:18:22,252 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 13:18:22,253 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 13:18:22,254 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 13:18:22,256 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 13:18:22,257 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 13:18:22,258 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 13:18:22,259 [INFO] yandextank.common.util util.py:546	Testing connection to resolved address 192.168.1.73 and port 9999
2021-09-16 13:18:22,260 [DEBUG] yandextank.common.util util.py:565	Exception on connect attempt [192.168.1.73]:9999 : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 561, in __test
    test_sock.connect(sa)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

2021-09-16 13:18:22,261 [INFO] yandextank.common.util util.py:549	Failed TCP connection test using [192.168.1.73]:9999
2021-09-16 13:18:22,262 [DEBUG] yandextank.common.util util.py:550	Failed TCP connection test using [192.168.1.73]:9999
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 547, in resolve
    self.__test(family, (parsed_ip, port))
  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 567, in __test
    raise RuntimeError(msg % (sa[0], sa[1]))
RuntimeError: TCP Connection test failed for [192.168.1.73]:9999, use phantom.connection_test=0 to disable it
2021-09-16 13:18:22,264 [ERROR] root consoleworker.py:268	Exception occurred:
<type 'exceptions.RuntimeError'>: All connection attempts failed for 192.168.1.73, use {phantom.connection_test: false} to disable it
  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/consoleworker.py", line 375, in run
    self.core.plugins_configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/core/tankcore.py", line 245, in plugins_configure
    plugin.configure()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 72, in configure
    self.phantom_config = self.phantom.config_file

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/plugin.py", line 81, in phantom
    self._phantom.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 95, in read_config
    stream.read_config()

  File "/usr/local/lib/python2.7/dist-packages/yandextank/plugins/Phantom/utils.py", line 275, in read_config
    self.address, do_test_connect, explicit_port)

  File "/usr/local/lib/python2.7/dist-packages/yandextank/common/util.py", line 555, in resolve
    raise RuntimeError(msg % address_str)

2021-09-16 13:18:22,266 [INFO] root consoleworker.py:269	Trying to clean up
2021-09-16 13:18:22,267 [INFO] yandextank.core.tankcore tankcore.py:561	Releasing lock: /var/lock/lunapark_pbmetd.lock
2021-09-16 13:18:22,272 [WARNING] root consoleworker.py:408	Job number is not available yet
2021-09-16 13:18:22,273 [WARNING] root consoleworker.py:415	Job number is not available yet
2021-09-16 13:18:22,278 [DEBUG] yandextank.core.tankcore tankcore.py:367	Collecting artifacts
2021-09-16 13:18:22,279 [INFO] yandextank.core.tankcore tankcore.py:368	Artifacts dir: /var/loadtest/logs/2021-09-16_13-18-22.140184
2021-09-16 13:18:22,280 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_stat_BOdlua.log to /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_stat_BOdlua.log
2021-09-16 13:18:22,281 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_stat_BOdlua.log
2021-09-16 13:18:22,283 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_H1szRI.log to /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_H1szRI.log
2021-09-16 13:18:22,284 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-18-22.140184/phantom_H1szRI.log
2021-09-16 13:18:22,285 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: validation_error.yaml to /var/loadtest/logs/2021-09-16_13-18-22.140184/validation_error.yaml
2021-09-16 13:18:22,287 [WARNING] yandextank.core.tankcore tankcore.py:424	File not found to collect: validation_error.yaml
2021-09-16 13:18:22,288 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-18-22.140184/phout__sJeLe.log to /var/loadtest/logs/2021-09-16_13-18-22.140184/phout__sJeLe.log
2021-09-16 13:18:22,289 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-18-22.140184/phout__sJeLe.log
2021-09-16 13:18:22,290 [DEBUG] yandextank.core.tankcore tankcore.py:422	Collecting file: /var/loadtest/logs/2021-09-16_13-18-22.140184/answ_QWPvKk.log to /var/loadtest/logs/2021-09-16_13-18-22.140184/answ_QWPvKk.log
2021-09-16 13:18:22,291 [WARNING] yandextank.core.tankcore tankcore.py:429	File already exists: /var/loadtest/logs/2021-09-16_13-18-22.140184/answ_QWPvKk.log
